# Generated by Django 5.2.11 on 2026-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_external_job_id_job_job_id_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='normalized_bills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
