# Generated by Django 5.2.11 on 2026-02-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_identifier', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('OCR', 'OCR'), ('LLM', 'LLM')], max_length=10)),
                ('input_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('output_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_units', models.IntegerField(default=0)),
                ('output_units', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='jobs.job')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.providermodel')),
            ],
        ),
    ]
