# Generated by Django 5.2.11 on 2026-02-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_providerusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermodel',
            name='input_cost_per_million',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='output_cost_per_million',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='api_call_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='input_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='output_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='input_unit_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Legacy: cost per 1000 units', max_digits=12),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='model_identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='output_unit_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Legacy: cost per 1000 units', max_digits=12),
        ),
        migrations.AlterField(
            model_name='providerusage',
            name='cost_estimated',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.IntegerField(help_text='Start of request range (e.g., 1)')),
                ('range_end', models.IntegerField(blank=True, help_text='End of request range (None for infinity)', null=True)),
                ('cost_per_1000_requests', models.DecimalField(decimal_places=6, max_digits=12)),
                ('provider_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='analytics.providermodel')),
            ],
            options={
                'ordering': ['range_start'],
            },
        ),
    ]
