# Generated by Django 5.2.11 on 2026-02-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_providermodel_input_cost_per_million_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providermodel',
            name='input_unit_cost',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='output_unit_cost',
        ),
    ]
